[package]
name = "kube-eks-config"
version = "0.1.0"
edition = "2024"
description = "Helper for creating kube::Config and kube::Client for EKS cluster"

[dependencies]
aws-config = { version = "1.8", features = ["behavior-version-latest"] }
aws-sdk-eks = "1.107"
http = "1.3"                                                             # Must be same as that of the `kube-client`
kube-client = "2.0"
# kube-client = { version = "0.88", default-features = false, features = [
#     "config",
# ] }
k8s-openapi = { version = "0.26", features = ["latest"] }


[dev-dependencies]
kube = "2.0"
tokio = { version = "1.47", features = ["full"] }
